export const pop = [
    {
        _id: "1",
        title: "HOSTEL MANAGEMENT SYSTEM",
        period: "2021",
        describe: "Lorem ipsum dolor sit, amet consectetur adipisicing elit.Optio fugiat dolorem obcaecati iure corrupti dicta natus, delectus possimus praesentium dignissimos consequatur at ipsam aperiam porro veniam explicabo voluptate deleniti nam.",
        technologies: ["army","b","c"],
        image: " https://www.shutterstock.com/image-vector/big-set-cute-sticker-concept-260nw-2133436391.jpg",
        link: 'https://www.google.co.in/',
        git:"https://github.com/",
    },

    {
        _id: "2",
        title: "LEAVE APPLICATION FOR EMPLOYEE",
        period: "2021",
        describe: "Jack In The Box lends voice to j-hope’s aspirations to break the mold and grow further. The album represents j-hope’s own musical personality and vision as an artist.Jack In The Box comprises a total of 10 tracks. The two main tracks, “MORE” and “Arson,” narrate the stories inside and outside the box respectively, conveying the core message that penetrates the whole album.",
        technologies: [],
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ-Ljxe88K-hlvw0p77WrNLBAgkdPCNRPSkTQ&s",
        link: "",
        git:"/",
    },

    {
        _id: "3",
        title: "MOVIE RECOMMENDED SYSTEM USING PYTHON",
        period: "2023",
        describe: "Lorem ipsum dolor sit, amet consectetur adipisicing elit.Optio fugiat dolorem obcaecati iure corrupti dicta natus, delectus possimus praesentium dignissimos consequatur at ipsam aperiam porro veniam explicabo voluptate deleniti nam.",
        technologies: [],
        image: "https://plus.unsplash.com/premium_photo-1673306778968-5aab577a7365?fm=jpg&q=60&w=3000&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8YmFja2dyb3VuZCUyMGltYWdlfGVufDB8fDB8fHww",
        link: "/",
        git:"/",
    },
    {
        _id: "4",
        title: "MOVIE RECOMMENDED SYSTEM USING PYTHON",
        period: "2023",
        describe: "Lorem ipsum dolor sit, amet consectetur adipisicing elit.Optio fugiat dolorem obcaecati iure corrupti dicta natus, delectus possimus praesentium dignissimos consequatur at ipsam aperiam porro veniam explicabo voluptate deleniti nam.",
        technologies: [],
        image: "https://plus.unsplash.com/premium_photo-1673306778968-5aab577a7365?fm=jpg&q=60&w=3000&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8YmFja2dyb3VuZCUyMGltYWdlfGVufDB8fDB8fHww",
        link: "/",
        git:"/",
    },
    {
        _id: "5",
        title: "MOVIE RECOMMENDED SYSTEM USING PYTHON",
        period: "2023",
        describe: "Lorem ipsum dolor sit, amet consectetur adipisicing elit.Optio fugiat dolorem obcaecati iure corrupti dicta natus, delectus possimus praesentium dignissimos consequatur at ipsam aperiam porro veniam explicabo voluptate deleniti nam.",
        technologies: [],
        image: "https://plus.unsplash.com/premium_photo-1673306778968-5aab577a7365?fm=jpg&q=60&w=3000&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8YmFja2dyb3VuZCUyMGltYWdlfGVufDB8fDB8fHww",
        link: "/",
        git:"/",
    },
    {
        _id: "6",
        title: "MOVIE RECOMMENDED SYSTEM USING PYTHON",
        period: "2023",
        describe: "Lorem ipsum dolor sit, amet consectetur adipisicing elit.Optio fugiat dolorem obcaecati iure corrupti dicta natus, delectus possimus praesentium dignissimos consequatur at ipsam aperiam porro veniam explicabo voluptate deleniti nam.",
        technologies: [],
        image: "https://plus.unsplash.com/premium_photo-1673306778968-5aab577a7365?fm=jpg&q=60&w=3000&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8YmFja2dyb3VuZCUyMGltYWdlfGVufDB8fDB8fHww",
        link: "/",
        git:"/",
    },
    
    
]